name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake SVG - tema claro
        uses: Platane/snk@v3
        with:
          github_user_name: Angelobelelli
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Gerar Snake SVG - tema escuro
        uses: Platane/snk@v3
        with:
          github_user_name: Angelobelelli
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          config: |
            theme: dark

      - name: Publicar SVGs no branch `output`
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
